[package]
name = "crusty-rustacean-api"
version = "0.1.0"
authors = ["Jeffery D. Mitchell", "<sentinel1909@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.7"
color-eyre = "0.6.2"
tokio = { version = "1.25.0", features = [ "macros", "rt-multi-thread" ]}
