[workspace]
members = [
  "cr-api",
  "."
]

[package]
name = "shuttle"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
axum = "0.6.8"
cr-api = { path = "./cr-api" }
shuttle-service = { version = "0.11.0", features = ["web-axum"] }
sync_wrapper = "0.1"