[package]
name = "cr-api"
version = "0.1.0"
authors = ["Jeffery D. Mitchell", "<sentinel1909@protonmail.com>"]
edition = "2021"

[lib]
path = "src/lib/lib.rs"

[[bin]]
name = "cr_api"
path = "src/bin/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.7"
hyper = "0.14.24"
serde = { version = "1.0.152", features = ["derive"] }
tokio = { version = "1.22.0", features = [ "macros", "rt-multi-thread" ]}

[dev-dependencies]
reqwest = "0.11.14"
