[package]
name = "cr-api-docker"
version = "0.1.0"
authors = ["Jeffery D. Mitchell", "<sentinel1909@protonmail.com>"]
edition = "2021"

[lib]
path = "src/lib/lib.rs"

[[bin]]
name = "cr_api_docker"
path = "src/bin/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.7", features = [ "form" ] }
axum-macros = "0.3.5"
chrono = { version = "0.4.22", default-features = false, features = ["clock"] }
config = "0.13.3"
env_logger = "0.10.0" 
hyper = "0.14.24"
once_cell = "1.17.1"
secrecy = { version = "0.8", features = [ "serde"] }
serde = { version = "1.0.152", features = ["derive"] }
tokio = { version = "=1.22.0", features = [ "macros", "rt-multi-thread" ]}
tower = "0.4.13"
tower-http = { version = "0.4.0", features = [ "trace", "request-id", "util" ] }
tracing = { version = "0.1.37", features = [ "log" ] }
tracing-bunyan-formatter = "0.3.6"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.16", features = [ "registry", "env-filter"] }
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
reqwest = "0.11.14"

[dependencies.sqlx]
version = "0.6"
default-features = false
features = [
  "runtime-tokio-native-tls",
  "macros",
  "postgres",
  "uuid",
  "chrono",
  "migrate",
  "offline"
]
